services:
  db:
    image: postgres:13
    container_name: food_manager_db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - external_network

  backend:
    container_name: food_manager_server
    image: pinkynrg/food_manager_backend:latest
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always
    networks:
      - external_network

networks:
  external_network:
    external: true